name: 🧠 Weekly System Summary Sync

on:
  schedule:
    - cron: '0 2 * * 0'  # Every Sunday at 2AM
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No requirements"

      - name: Run System Summary Sync
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          GRAFANA_DASHBOARD_UID: ${{ secrets.GRAFANA_DASHBOARD_UID }}
          GRAFANA_SUMMARY_PANEL_ID: ${{ secrets.GRAFANA_SUMMARY_PANEL_ID }}
        run: |
          python summarize_system_logs_with_ollama.py
          python obsidian_update_from_logs.py
          python grafana_summary_updater.py
